title: Injin Woo
logo: /assets/img/thumbnail.jpg
description: |
  蓋將自其變者而觀之，而天地曾不能以一瞬；自其不變者而觀之，則物與我皆無盡也。
  When viewed from a changing perspective, the universe can hardly be the same even within a blink of an eye; but when looked at from an unchanging perspective, everything conserves itself, and so do we.

navigation:
  - title: Home
    title_ko: 홈
    url: /
  - title: About
    title_ko: 소개
    url: /about
  - title: Research
    title_ko: 연구
    url: /research
  - title: Talks
    title_ko: 발표
    url: /presentation
  - title: Other Writing
    title_ko: 기타 글
    url: /blog
  - title: CV
    title_ko: 이력서
    url: /cv

show_downloads: false
google_analytics:
# GoatCounter 사이트 코드 (https://<코드>.goatcounter.com 의 <코드> 부분)
goatcounter: injinwoo
theme: jekyll-theme-minimal
url: https://injin-woo-phil.github.io
plugins:
  - jekyll-sitemap

collections:
  blog:
    output: true
    permalink: /blog/:name/

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "entry"

exclude:
  - 관리가이드.md
