title: Injin Woo
logo: /assets/img/logo.png
description: I received a B.A. in Philosophy and Korean Literature in Classical Chinese. I’m most interested in ontology and meta-ontology, especially ontological nominalism and ontological deflationism, as well as in inferentialism on meaning. I’m also interested in Skepticism and Buddhism. Outside philosophy, I enjoy reading and memorizing 18th-century Korean literature and Song dynasty literature. Also love to listen to 80s jazz music, heavy metal, and Korean traditional music. I play Guitar/Piri(a Korean traditional instrument) if there is time left.

you can contact me at jaegoi53@gmail.com

show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
