title: Injin Woo
logo: /assets/img/thumbnail.png
description: |
  蓋將自其變者而觀之﹐而天地曾不能一瞬;  
  自其不變者而觀之﹐則物于我皆無盡也。  
  When viewed from a changing perspective, the universe can hardly be the same even within a blink of an eye,  
  But when looked at from an unchanging perspective, everything conserves itself, and so do we.  
  
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Research
    url: /research
  - title: Blog
    url: /blog
  - title: Contact
    url: /contact


show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
